const keys: Array<{keyClass: string, keyStyle: string, keyName: string}> = [
    {keyClass: 'key', keyStyle: '0%', keyName: 'A (До)'},
    {keyClass: 'key', keyStyle: '6.66%', keyName: 'S (Ре)'},
    {keyClass: 'key', keyStyle: '13.32%', keyName: 'D (Ми)'},
    {keyClass: 'key', keyStyle: '19.98%', keyName: 'F (Фа)'},
    {keyClass: 'key', keyStyle: '26.64%', keyName: 'G (Соль)'},
    {keyClass: 'key', keyStyle: '33.3%', keyName: 'H (Ля)'},
    {keyClass: 'key', keyStyle: '39.96%', keyName: 'J (Си)'},
    {keyClass: 'key', keyStyle: '46.62%', keyName: 'K (До)'},
    {keyClass: 'key', keyStyle: '53.28%', keyName: 'L (Ре)'},
    {keyClass: 'key', keyStyle: '59.94%', keyName: ': (Ми)'},
    {keyClass: 'key', keyStyle: '66.6%', keyName: '" (Фа)'},
    {keyClass: 'key', keyStyle: '73.26%', keyName: '| (Соль)'},
    {keyClass: 'key', keyStyle: '79.92%', keyName: '4 (Ля)'},
    {keyClass: 'key', keyStyle: '86.58%', keyName: '5 (Си)'},
    {keyClass: 'key', keyStyle: '93.24%', keyName: '6 (До)'},
    {keyClass: 'blackKey', keyStyle: '4%', keyName: 'W (До#)'},
    {keyClass: 'blackKey', keyStyle: '10.8%', keyName: 'E (Ре#)'},
    {keyClass: 'blackKey', keyStyle: '24.1%', keyName: 'T (Фа#)'},
    {keyClass: 'blackKey', keyStyle: '30.8%', keyName: 'Y (Соль#)'},
    {keyClass: 'blackKey', keyStyle: '37.5%', keyName: 'U (Ля#)'},
    {keyClass: 'blackKey', keyStyle: '50.9%', keyName: 'O (До#)'},
    {keyClass: 'blackKey', keyStyle: '57.6%', keyName: 'P (Ре#)'},
    {keyClass: 'blackKey', keyStyle: '71%', keyName: '{ (Фа#)'},
    {keyClass: 'blackKey', keyStyle: '77.7%', keyName: '7 (Соль#)'},
    {keyClass: 'blackKey', keyStyle: '84.4%', keyName: '8 (Ля#)'},
]

export default keys